site_name: MkDocs Maria Gutierrez
site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.download
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: cyan
      accent: teal

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  <div style="display: flex; justify-content: space-between; align-items: center;">
    <span>&copy; 2024 <a href="https://github.com/mariagutierrez03" target="_blank" rel="noopener">María Gutiérrez</a></span>
    <img src="./fotos/cc_github.png" alt="Descripción de la imagen" style="width:100px;height:auto; margin-left:1060px;">
  </div>
